name: dvpn-node-initialize

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  role_to_assume: arn:aws:iam::103309208207:role/dvpn-node-initialize

jobs:
  initialize:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        # region: ["eu-west-3", "eu-north-1"]
        region: ["eu-west-3"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Python dependencies
        working-directory: ./cdk/initialize/
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
      - name: Install CDK
        run: |
          npm install --global aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ matrix.region }}
          role-to-assume: ${{ env.role_to_assume }}
      - name: Deploy to AWS
        working-directory: ./cdk/initialize/
        run: cdk deploy
        env:
          AWS_REGION: ${{ matrix.region }}
