name: dvpn-node-initialize

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

env:
  role_to_assume: arn:aws:iam::103309208207:role/dvpn-node-initialize

jobs:
  initialize:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        region: ["eu-west-3", "eu-north-1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.role_to_assume }}
          aws-region: ${{ matrix.region }}
      - name: Deploy to AWS
        run: cdk deploy
        working-directory: ./cdk/initialize/
        env:
          AWS_REGION: ${{ matrix.region }}
